In [3]:
import numpy as np
np.__version__


'2.0.0'

In [13]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



Create An Array

In [4]:
arr1 = np.arange(0,100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.arange ? # This is to know about function

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [18]:
arr3= np.arange(0,100,4)

In [19]:
arr3

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [5]:
arr4= np.arange(-100,0)
arr4

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1])

In [5]:
# To Reshape an Array
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Python list
List comprehension
array module(import lib array)
numpy array:
-> zeros
-> Ones
-> full
-> eye
->Arrange
-> Reshape


# Diffrence between list and array
list : we can put diffrent type elements.
Array : we can only put same type of element.
list : Required more time
Array : Required less time
list : It store hetroginious type of data
Array : It store homoginious type of data

In [6]:
lst = list(range(0,10)) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
l2 = [x for x in range(0,10)]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
l3 = [str(x) for x in range(0,10)] 
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
l4 = [x**2 for x in range(0,10)]  # To square given list
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [11]:
l5 = [type(x) for x in range(0,10)]
l5

[int, int, int, int, int, int, int, int, int, int]

# To import Array

In [16]:
import array as arr

In [14]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [18]:
a = arr.array('i',l2)
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr1 = arr.array('i',[x**2 for x in l2])
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [22]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.array([x+3 for x in l2])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
np.array([l2],dtype = float)

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [30]:
# 2-D List
l2d = [[1,2,3],[3,4,5]]
l2d

[[1, 2, 3], [3, 4, 5]]

In [36]:
l3d =[range(i,i+3) for i in [1,3]]
np.array(l3d)

array([[1, 2, 3],
       [3, 4, 5]])

In [43]:
l4d =[range(i,i+3) for i in [1,3,2]]
np.array(l4d)

array([[1, 2, 3],
       [3, 4, 5],
       [2, 3, 4]])

In [45]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [48]:
z = np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
o = np.ones((10,10))
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
z[3:7,3:7]=7
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
z[4:6,4:6]=6
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 7., 6., 6., 7., 8., 9., 0.],
       [0., 9., 8., 7., 6., 6., 7., 8., 9., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
arr8 = np.full((3,3),3.14)
arr8

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

# eye() function for identity matrix

In [71]:
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

In [70]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [73]:
np.transpose(np.eye(8))

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])