In [1]:
import numpy as np
np.__version__


'2.0.0'

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



Create An Array

In [4]:
arr1 = np.arange(0,100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
# np.arange? # This is to know about function

In [6]:
arr3= np.arange(0,100,4)

In [7]:
arr3

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [8]:
arr4= np.arange(-100,0)
arr4

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1])

In [9]:
# To Reshape an Array
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Python list
List comprehension
array module(import lib array)
numpy array:
-> zeros
-> Ones
-> full
-> eye
->Arrange
-> Reshape


# Diffrence between list and array
list : we can put diffrent type elements.
Array : we can only put same type of element.
list : Required more time
Array : Required less time
list : It store hetroginious type of data
Array : It store homoginious type of data

In [10]:
lst = list(range(0,10)) 

In [11]:
l2 = [x for x in range(0,10)]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
l3 = [str(x) for x in range(0,10)] 
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
l4 = [x**2 for x in range(0,10)]  # To square given list
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [14]:
l5 = [type(x) for x in range(0,10)]
l5

[int, int, int, int, int, int, int, int, int, int]

# To import Array

In [15]:
import array as arr

In [16]:
# help(array)

In [17]:
a = arr.array('i',l2)
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr1 = arr.array('i',[x**2 for x in l2])
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [19]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.array([x+3 for x in l2])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
np.array([l2],dtype = float)

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [22]:
# 2-D List
l2d = [[1,2,3],[3,4,5]]
l2d

[[1, 2, 3], [3, 4, 5]]

In [23]:
l3d =[range(i,i+3) for i in [1,3]]
np.array(l3d)

array([[1, 2, 3],
       [3, 4, 5]])

In [24]:
l4d =[range(i,i+3) for i in [1,3,2]]
np.array(l4d)

array([[1, 2, 3],
       [3, 4, 5],
       [2, 3, 4]])

In [25]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
z = np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
o = np.ones((10,10))
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
z[3:7,3:7]=7
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
z[4:6,4:6]=6
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 6., 6., 7., 0., 0., 0.],
       [0., 0., 0., 7., 6., 6., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
arr8 = np.full((3,3),3.14)
arr8

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

# eye() function for identity matrix

In [33]:
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

In [135]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.transpose(np.eye(8))

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
arr9=np.full((6,6),64)
arr9

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

Linspace - Linearly spaced elements

In [37]:
np.linspace(0,1,5) # starting value,ending value,number of times

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000016132924540>
File:            c:\users\ayush\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting

In [40]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

Random Function
# btw 0 to 1

In [41]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\Ayush\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\ayush\appdata\local\programs\python\python312\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============

In [42]:
np.random.random((3,3))

array([[0.39368334, 0.80018422, 0.29137476],
       [0.03468805, 0.34219603, 0.94256393],
       [0.62905582, 0.3686176 , 0.94212965]])

Normal Function - 
value with mean 0 to 1

In [43]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [44]:
np.random.normal(0,1,10)

array([ 0.26534832,  1.44036028,  0.20450069, -0.32160418, -1.33886616,
       -1.54878511,  0.19397755,  0.33840891,  1.01327315, -1.08991136])

In [45]:
np.random.normal(2,2,10)

array([-0.04250269, -0.201851  ,  3.87530488,  4.350545  ,  1.60518093,
        5.51427408,  1.43918719,  0.403754  , -2.83757318,  1.94030972])

Seed Function
in this random values will not change

In [46]:
np.random.seed(5)
np.random.random(10)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [131]:
np.random.randn?

<bound method RandomState.randn of RandomState(MT19937) at 0x16132AC4A40>

In [48]:
np.random.randn(2,4)

array([[ 0.18760323, -0.32986996, -1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 , -1.66478853, -0.70017904]])

Operation on Numpy

In [49]:
arr1=np.random.randint(0,100,20)
arr1

array([ 9, 41, 62,  1, 82, 16, 78,  5, 58,  0, 80,  4, 36, 51, 27, 31,  2,
       68, 38, 83], dtype=int32)

In [50]:
arr1.ndim  # To check number of dimension

1

In [51]:
arr1.size # To check total number of elements

20

In [52]:
arr1.shape # To check shape

(20,)

In [53]:
arr1.dtype # To check dtype of array

dtype('int32')

Array Indexing

In [54]:
arr=np.random.randint(0,40,10)
arr

array([19, 18,  7, 36, 30, 11,  3,  1,  3, 27], dtype=int32)

In [55]:
arr[:4]

array([19, 18,  7, 36], dtype=int32)

In [56]:
arr[-5]

np.int32(11)

In [57]:
arr[3]=10

In [58]:
arr

array([19, 18,  7, 10, 30, 11,  3,  1,  3, 27], dtype=int32)

In [59]:
arr[2]=9
arr

array([19, 18,  9, 10, 30, 11,  3,  1,  3, 27], dtype=int32)

# Numpy Assigments

In [60]:
# Q1
a=np.array([1,2,3])
a

array([1, 2, 3])

In [61]:
b=np.random.randint(1,10,(2,2))
b

array([[2, 6],
       [8, 1]], dtype=int32)

In [62]:
c=np.arange(0,27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
#Q2
c.dtype

dtype('int64')

In [64]:
# Q3
a.shape
a.ndim

1

In [65]:
b.shape
b.ndim

2

In [66]:
c.shape
c.ndim

3

In [67]:
# Q4
d = np.zeros(12)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
# Q5
e = np.ones((2,2))
e

array([[1., 1.],
       [1., 1.]])

In [69]:
# Q6
np.random.seed(10)
math = np.random.randint(0,100,20)
math

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0, 40, 36, 16, 11, 54, 88, 62,
       33, 72, 78], dtype=int32)

In [70]:
# Q12
np.eye(4,4)+5

array([[6., 5., 5., 5.],
       [5., 6., 5., 5.],
       [5., 5., 6., 5.],
       [5., 5., 5., 6.]])

In [71]:
# Q13
#np.arange?

In [72]:
# Q18
g=np.arange(0,25).reshape(5,5)
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Indexing

In [73]:
arr=[1,2,3,4,5,6]
arr

[1, 2, 3, 4, 5, 6]

In [74]:
arr[:3]

[1, 2, 3]

In [75]:
arr[::2]

[1, 3, 5]

# To reverse the array in order

In [76]:
arr[::-1]

[6, 5, 4, 3, 2, 1]

In [77]:
arr2 = np.random.randint(0,100,(5,5))
arr2

array([[49, 51, 54, 77, 69],
       [13, 25, 13, 92, 86],
       [30, 30, 89, 12, 65],
       [31, 57, 36, 27, 18],
       [93, 77, 22, 23, 94]], dtype=int32)

In [78]:
arr2[0:3,1:3]

array([[51, 54],
       [25, 13],
       [30, 89]], dtype=int32)

In [79]:
arr2[2:4,1:3]

array([[30, 89],
       [57, 36]], dtype=int32)

In [118]:
arr4 = np.zeros((8,8))
arr4[::2,::2]=1
arr4[1::2,1::2]=1
arr4

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# Shallow copy and Deep copy

# Shallow copy

In [82]:
np.random.seed(101)
arr5 = np.random.randint(0,100,(5,5))
arr5

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40],
       [ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40],
       [49, 83,  8, 29, 59]], dtype=int32)

In [83]:
arr6 = arr5[2:5,0:3]
arr6

array([[ 4, 63, 40],
       [64,  5, 12],
       [49, 83,  8]], dtype=int32)

In [84]:
arr6[2,2]=19
arr6

array([[ 4, 63, 40],
       [64,  5, 12],
       [49, 83, 19]], dtype=int32)

In [85]:
arr5 # here in main matrix number is also changed when it is changed in sub part "arr6"

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40],
       [ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40],
       [49, 83, 19, 29, 59]], dtype=int32)

# Deep copy

In [86]:
arr7=arr5[2:5,2:5].copy()
arr7

array([[40, 60, 92],
       [12, 93, 40],
       [19, 29, 59]], dtype=int32)

In [87]:
arr7[2,1]=40
arr7

array([[40, 60, 92],
       [12, 93, 40],
       [19, 40, 59]], dtype=int32)

In [88]:
arr7

array([[40, 60, 92],
       [12, 93, 40],
       [19, 40, 59]], dtype=int32)

In [89]:
arr5

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40],
       [ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40],
       [49, 83, 19, 29, 59]], dtype=int32)

In [90]:
arrr = np.arange(0,3) # making 1D array horizontaly
arrr.reshape(3,1)# makin same array verticaly

array([[0],
       [1],
       [2]])

In [91]:
arrrr=np.arange(1,17) # making an array
b = arrrr.reshape(4,4) # making in a 2D array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
b.reshape(1,16) #then again reshape in 1D array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [93]:
# returning ravel array
#np.ravel?
np.ravel(b,order = "F")

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

In [94]:
# returning Flatten
np.flatten?

Object `np.flatten` not found.


In [95]:
c = b.flatten()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [96]:
c[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

# Stacks

In [154]:
np.hstack?

Signature:       np.hstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.hstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hstack at 0x00000161328F5620>
File:            c:\users\ayush\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\shape_base.py
Docstring:      
Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D
arrays where it concatenates along the first axis. Rebuilds arrays divided
by `hsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the second axis,
    except 1-D arrays which can

In [136]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
arrr = np.arange(7,10)
arrr

array([7, 8, 9])

In [149]:
b=arrr[:,np.newaxis]
b

array([[7],
       [8],
       [9]])

In [163]:
np.hstack((arr,b,1))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [146]:
# split
#np.split?
#np.hsplit?
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000016132A52D40>
File:            c:\users\ayush\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]
>>

In [159]:
a =np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [161]:
np.split(a,[1,4,6])

[array([1]), array([2, 3, 4]), array([5, 6]), array([], dtype=int64)]

In [166]:
c = np.arange(0,20).reshape(5,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [170]:
np.vsplit(c,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

# Arguments

In [178]:
c = np.arange(0,20).reshape(5,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [172]:
np.min(c)

np.int64(0)

In [175]:
np.sum(c,axis = 1)

array([ 6, 22, 38, 54, 70])

In [176]:
np.prod(c)

np.int64(0)

In [177]:
g = -1
np.abs(g)

np.int64(1)

In [180]:
np.argmin(c)

np.int64(0)

In [181]:
np.argmax(c)

np.int64(19)

In [182]:
np.var(c)

np.float64(33.25)