In [1]:
import numpy as np

In [3]:
ar1=np.zeros(10)

In [5]:
ar1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
ar2=np.ones(10)

In [9]:
ar2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
ar=np.arange(10,50)

In [17]:
ar


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
ar_even=np.arange(10,50,2)

In [21]:
ar_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [25]:
matrix=np.arange(0,9).reshape(3,3)

In [29]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
identity_mat=np.eye(3)

In [33]:
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
num=np.random.random()

In [49]:
print(num)

0.7357252290260746


In [51]:
num_std_nor=np.random.random(25)


In [53]:
num_std_nor

array([0.06247809, 0.8951379 , 0.58393807, 0.26030803, 0.57081687,
       0.76473334, 0.8954709 , 0.74942771, 0.3957154 , 0.8580052 ,
       0.82573595, 0.3257091 , 0.00174693, 0.27945939, 0.37505447,
       0.92341951, 0.16996024, 0.41698808, 0.31245796, 0.58026839,
       0.69717948, 0.88305745, 0.27492195, 0.83722452, 0.67097973])

In [73]:
elemnets=np.linspace(0.01,1,100)

In [75]:
elemnets

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [77]:
matrix_new=elemnets.reshape((10,10))

In [79]:
matrix_new

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [81]:
lin_20=np.linspace(0,1,20)

In [83]:
lin_20

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [85]:
matrix_20=lin_20.reshape((4,5))

In [87]:
matrix_20

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [95]:
readymade=np.arange(1,26).reshape(5,5)

In [97]:
readymade

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [99]:
readymade[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [105]:
readymade[3,4]

20

In [119]:
readymade[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [121]:
readymade[4:,:]

array([[21, 22, 23, 24, 25]])

In [123]:
readymade[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [125]:
np.sum(readymade)

325

In [127]:
np.sum(readymade,axis=0)

array([55, 60, 65, 70, 75])

In [129]:
np.sum(readymade,axis=1)

array([ 15,  40,  65,  90, 115])

In [131]:
np.std(readymade,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [133]:
np.var(readymade,axis=1)

array([2., 2., 2., 2., 2.])

In [135]:
np.min(readymade,axis=1)

array([ 1,  6, 11, 16, 21])

In [137]:
np.max(readymade,axis=1)

array([ 5, 10, 15, 20, 25])

In [139]:
nan_matrix= np.full((5,5), np.nan)

In [141]:
nan_matrix

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [143]:
nan_matrix[1:4,1:4]=0

In [145]:
nan_matrix

array([[nan, nan, nan, nan, nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan, nan, nan, nan, nan]])