In [3]:
import numpy as np

In [4]:
arr_1d=np.arange(10)

In [5]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr_2d=np.arange(10).reshape(2,5)

In [7]:
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
arr_3d=np.arange(12).reshape(3,4)

In [9]:
arr_3d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
type(arr_1d)

numpy.ndarray

In [11]:
np.shape(arr_1d)


(10,)

In [12]:
np.shape(arr_2d)


(2, 5)

In [13]:
np.shape(arr_3d)

(3, 4)

In [28]:
ar1=np.zeros(12)

In [30]:
ar1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
ar2=np.ones(12).reshape(2,6)

In [34]:
ar2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
Maths_Marks=np.random.randint(0,101,20)


In [42]:
Maths_Marks

array([67, 71, 35, 82, 59, 36, 17,  5, 62, 47, 23, 38, 52, 86, 73, 68, 77,
       16, 50, 34])

In [50]:
np.sort(Maths_Marks)


array([ 5, 16, 17, 23, 34, 35, 36, 38, 47, 50, 52, 59, 62, 67, 68, 71, 73,
       77, 82, 86])

In [52]:
np.sort(Maths_Marks)[::-1]

array([86, 82, 77, 73, 71, 68, 67, 62, 59, 52, 50, 47, 38, 36, 35, 34, 23,
       17, 16,  5])

In [54]:
Maths_Marks_copy=Maths_Marks.copy()

In [56]:
Maths_Marks_copy

array([67, 71, 35, 82, 59, 36, 17,  5, 62, 47, 23, 38, 52, 86, 73, 68, 77,
       16, 50, 34])

In [58]:
ar_new=np.eye(5)

In [60]:
ar_new

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
converted=ar_new.flatten()

In [72]:
converted

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [74]:
trial_ar=np.arange(0,9).reshape(3,3)

In [76]:
trial_ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
add_col=np.arange(10,13)

In [80]:
add_col

array([10, 11, 12])

In [96]:
new=np.vstack([trial_ar, add_col])

In [98]:
new

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12]])

In [100]:
v=np.vsplit(new,2)

In [102]:
v

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [10, 11, 12]])]

In [108]:
h=np.hsplit(new,3)

In [110]:
h

[array([[ 0],
        [ 3],
        [ 6],
        [10]]),
 array([[ 1],
        [ 4],
        [ 7],
        [11]]),
 array([[ 2],
        [ 5],
        [ 8],
        [12]])]

In [116]:
ar_4x4=np.eye(4)

In [118]:
ar_4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [120]:
ar_4x4+4


array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [122]:
float_ar=np.array([1.242,7.987,9.098,6.777,5.990])

In [126]:
ceiling=np.ceil(float_ar)

In [128]:
ceiling

array([ 2.,  8., 10.,  7.,  6.])

In [132]:
flooring=np.floor(float_ar)

In [134]:
flooring

array([1., 7., 9., 6., 5.])

In [136]:
round_up=np.round(float_ar,2)

In [138]:
round_up

array([1.24, 7.99, 9.1 , 6.78, 5.99])

In [140]:
matrix_5x5=np.arange(0,25).reshape(5,5)

In [142]:
matrix_5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [146]:
np.min(matrix_5x5,0)

array([0, 1, 2, 3, 4])

In [148]:
np.max(matrix_5x5,0)

array([20, 21, 22, 23, 24])

In [152]:
np.std(matrix_5x5,0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [156]:
np.var(matrix_5x5,0)

array([50., 50., 50., 50., 50.])

In [160]:
null_vector=np.zeros(10)

In [164]:
null_vector

array([  0.,   0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.])

In [162]:
null_vector[6]=200

In [166]:
null_vector

array([  0.,   0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.])

In [170]:
arrr=np.arange(100,150)

In [172]:
arrr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [178]:
arrr[::-1]

array([149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111,
       110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [182]:
function_matrix=np.arange(25).reshape(5,5)

In [184]:
function_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [186]:
zero_ar=[1,0,2,0,0,4,0,8]

In [188]:
zero_ar

[1, 0, 2, 0, 0, 4, 0, 8]

In [196]:
zeross=np.nonzero(zero_ar)[0]

In [198]:
zeross

array([0, 2, 5, 7], dtype=int64)

In [242]:
mat_10x10=np.ones(100).reshape(10,10)

In [244]:
mat_10x10

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [250]:
mat_10x10[1:9,1:9]=0

In [252]:
mat_10x10

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [254]:
checker=np.zeros(64).reshape(8,8)

In [256]:
checker

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [258]:
checker[1::2,::2]= 1
checker[::2,1::2]= 1

In [260]:
checker

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [262]:
matrix1=np.random.randint(0,10,(3,3))

In [264]:
matrix2=np.random.randint(0,10,(3,3))


In [266]:
sumation=matrix1+matrix2

In [268]:
sumation

array([[16, 13, 11],
       [ 3, 16, 15],
       [12, 10,  9]])

In [270]:
product=matrix1*matrix2

In [272]:
product

array([[63, 40, 30],
       [ 2, 64, 54],
       [32, 24,  8]])

In [274]:
difference=matrix1-matrix2

In [276]:
difference

array([[-2,  3, -1],
       [-1,  0, -3],
       [ 4,  2, -7]])

In [278]:
div=matrix1/matrix2

In [280]:
div

array([[0.77777778, 1.6       , 0.83333333],
       [0.5       , 1.        , 0.66666667],
       [2.        , 1.5       , 0.125     ]])