In [1]:
import numpy as np

In [5]:
aar1d=np.random.random(6)
aar1d

array([0.74542288, 0.61546012, 0.84923537, 0.78371768, 0.89438393,
       0.92651471])

In [11]:
aar2d=np.random.random((6,6))
aar2d

array([[0.52465949, 0.47678342, 0.86740322, 0.83788101, 0.22644069,
        0.45242307],
       [0.30351372, 0.5120248 , 0.93257674, 0.93926105, 0.00597393,
        0.02466559],
       [0.00973027, 0.82123853, 0.7830783 , 0.56841367, 0.4465208 ,
        0.78275951],
       [0.15396846, 0.42107747, 0.64284655, 0.38833177, 0.7693864 ,
        0.90293463],
       [0.37475629, 0.51197276, 0.53531147, 0.27129744, 0.04536952,
        0.95590762],
       [0.76551872, 0.35828777, 0.50619585, 0.32067628, 0.03611516,
        0.58202197]])

In [29]:
aar3d=np.random.random((3,3,2))
aar3d

array([[[0.91415413, 0.09828484],
        [0.46988987, 0.82684519],
        [0.87569728, 0.43546415]],

       [[0.79658023, 0.24106962],
        [0.79853431, 0.52626058],
        [0.57260418, 0.45805611]],

       [[0.48820799, 0.46899163],
        [0.32089262, 0.81317285],
        [0.4005081 , 0.47097373]]])

In [31]:
aar2d.dtaype()

AttributeError: 'numpy.ndarray' object has no attribute 'dtaype'

In [35]:
aar1d.shape

(6,)

In [37]:
aar1d.size

6

In [39]:
aar1d.dtype

dtype('float64')

In [41]:
aar1d.ndim

1

In [43]:
f=np.ones((2,2))
f

array([[1., 1.],
       [1., 1.]])

In [ ]:
g=np.random.seed(10)
math=